default: &default
  adapter: postgresql
  timeout: 5000
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: learning_dev

test:
  <<: *default
  database: learning_test

production:
  <<: *default
  database: learning_prod
